### ISSUE TITLE
Archiving repo

### ISSUE THREAD

**Issue by bsipocz** [astroML/astroML_addons#4]
@jakevdp - What do you think about archiving this repo? The content has been moved upstream to astropy already. 
We can always reopen if any other modules in astroML needs to Cython/C separately.

**Comment by jakevdp** [comment]
Sure, sounds good.

**Comment by jakevdp** [comment]
Honestly, if I'd known more about setting up and building packages 7 years ago, this repo wouldn't exist :smile:
